branch_whitelist = [ "main" ]
ignore_merge_commits = true

pre_bump_hooks = [
    "cargo test -- --test-threads 1",
    "cargo clippy",
    "cargo build --release --jobs 1",
    "cargo fmt --all",
    "cargo set-version {{version}}",
]

post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "cargo package",
    "cargo publish"
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "musicbrainz_rs_nova"
owner = "RustyNova"
authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
    { signature = "okno", username = "oknozor" },
    { signature = "Ritiek Malhotra", username = "ritiek" },
    { signature = "Yesterday17", username = "Yesterday17" },
    { signature = "snylonue", username = "snylonue" },
    { signature = "nappa85", username = "Marco Napetti" },
    { signature = "RustyNova", username = "RustyNova" },
]
